version: 2
jobs:

  build:
    docker:
      - image: mrseccubus/github-pages:latest
    steps:
      - run: (cd /root/;rm -rf project;mkdir project)
      - checkout
      - run:
          name: Build site www.divd.nl
          command: |
            cd www.divd.nl;
            jekyll build 2>&1|grep -v 'warning:';
            cd ..
      - run:
          name: Build site csirt.divd.nl
          command: |
            cd csirt.divd.nl;
            jekyll build 2>&1|grep -v 'warning:';
            cd ..
      - run:
          name: Test HTML
          command: |
            for site in www.divd.nl csirt.divdi.nl; do
              ( echo "Checking $site; cd $site ; ./proof_html.sh ) 
            done
      - save_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/root/project/www.divd.nl/_site"
            - "/root/project/csirt.divd.nl/_site"
            - "/root/project/.htaccess"


  upload:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install software
          command: |
            apk update;
            apk add rsync openssh sshpass;
            echo "set ftp:passive-mode true" > ~/.lftprc
      - restore_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Upload
          command: |
            mkdir ~/.ssh;
            echo  "upload.bit.nl,213.136.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIVx+0N0LECcGHPywPCk9uz4/l3kNUVNe5QQRleIkMCTarkYauvRrPNPl49x3LIjF6cZsmQZX7jwgsJqEzfcF98=" > ~/.ssh/known_hosts;
            cd /root/project/;
            sshpass -e rsync -av .htaccess www-divd@upload.bit.nl:htdocs;
            cd /root/project/csirt.divd.nl/_site;
            sshpass -e rsync -av . www-divd@upload.bit.nl:htdocs/securitymeldpunt-nl;
            cd /root/project/www.divd.nl/_site;
            sshpass -e rsync -av . www-divd@upload.bit.nl:htdocs/divd-nl;

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only:
                - master
