theme: jekyll-theme-cayman

paginate: 10
plugins: [jekyll-paginate]
paginate_path: "blog/:num/"

language: nl-nl

title: DIVD CSIRT
description: "Voorheen / Previously : Het Nederlandse Security Meldpunt / Dutch Security Hotline"
#description: Het Nederlandse meldpunt voor kwetsbaarheden, infecties en andere (cyber)security gerelateerde zaken.
repository: DIVD-NL/sites

timezone: Europe/Amsterdam
future: true
encoding: utf-8

permalink: pretty
markdown: kramdown
show_downloads: false
github:
  is_project_page: false

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-secinfo

jekyll-secinfo:
  divd:
    url: /cases/DIVD-

# Custom headers
webrick:
  headers:
    Content-Security-Policy: default-src 'none'; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; script-src 'self' ; style-src 'self' https://fonts.googleapis.com/; connect-src 'self';

# Collections
collections:
  team:
    output: false
  cves:
    output: true

exclude:
  - README.md
  - serve*
  - "*.sh"
  - .keep
  - Gemfile
  - Gemfile.lock
  - "*.conf"
